// This file is automatically generated by qtc from "svg.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line templates/svg.qtpl:1
package templates

//line templates/svg.qtpl:1
import "github.com/doctor-fate/mskix/device"

//line templates/svg.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/svg.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/svg.qtpl:4
type RectangleConfiguration struct {
	Width, Height int
	Style         string
}

type TextConfiguration struct {
	FontSize int
}

type ArrowConfiguration struct {
	HorizontalLength               int
	HorizontalShift, VerticalShift int
	Style                          string
}

type Configuration struct {
	Width, Height int
	RC            RectangleConfiguration
	TC            TextConfiguration
	AC            ArrowConfiguration
}

type Translate struct {
	Horizontal, Vertical int
}

//line templates/svg.qtpl:31
func StreamHeader(qw422016 *qt422016.Writer, configuration Configuration) {
	//line templates/svg.qtpl:31
	qw422016.N().S(`<?xml version="1.0"?>
<svg width="`)
	//line templates/svg.qtpl:32
	qw422016.N().D(configuration.Width)
	//line templates/svg.qtpl:32
	qw422016.N().S(`" height="`)
	//line templates/svg.qtpl:32
	qw422016.N().D(configuration.Width)
	//line templates/svg.qtpl:32
	qw422016.N().S(`" xmlns="http://www.w3.org/2000/svg">
`)
	//line templates/svg.qtpl:33
}

//line templates/svg.qtpl:33
func WriteHeader(qq422016 qtio422016.Writer, configuration Configuration) {
	//line templates/svg.qtpl:33
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/svg.qtpl:33
	StreamHeader(qw422016, configuration)
	//line templates/svg.qtpl:33
	qt422016.ReleaseWriter(qw422016)
	//line templates/svg.qtpl:33
}

//line templates/svg.qtpl:33
func Header(configuration Configuration) string {
	//line templates/svg.qtpl:33
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/svg.qtpl:33
	WriteHeader(qb422016, configuration)
	//line templates/svg.qtpl:33
	qs422016 := string(qb422016.B)
	//line templates/svg.qtpl:33
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/svg.qtpl:33
	return qs422016
	//line templates/svg.qtpl:33
}

//line templates/svg.qtpl:35
func StreamTitle(qw422016 *qt422016.Writer, id device.ID) {
	//line templates/svg.qtpl:35
	qw422016.N().S(`
<text x="55%" y="50" text-anchor="middle" font-size="44">`)
	//line templates/svg.qtpl:36
	qw422016.E().S(string(id))
	//line templates/svg.qtpl:36
	qw422016.N().S(`</text>
`)
	//line templates/svg.qtpl:37
}

//line templates/svg.qtpl:37
func WriteTitle(qq422016 qtio422016.Writer, id device.ID) {
	//line templates/svg.qtpl:37
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/svg.qtpl:37
	StreamTitle(qw422016, id)
	//line templates/svg.qtpl:37
	qt422016.ReleaseWriter(qw422016)
	//line templates/svg.qtpl:37
}

//line templates/svg.qtpl:37
func Title(id device.ID) string {
	//line templates/svg.qtpl:37
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/svg.qtpl:37
	WriteTitle(qb422016, id)
	//line templates/svg.qtpl:37
	qs422016 := string(qb422016.B)
	//line templates/svg.qtpl:37
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/svg.qtpl:37
	return qs422016
	//line templates/svg.qtpl:37
}

//line templates/svg.qtpl:39
func StreamRecordRight(qw422016 *qt422016.Writer, record device.Record, translate Translate, configuration Configuration) {
	//line templates/svg.qtpl:39
	qw422016.N().S(`
<g transform="translate(`)
	//line templates/svg.qtpl:40
	qw422016.N().D(translate.Horizontal)
	//line templates/svg.qtpl:40
	qw422016.N().S(`,`)
	//line templates/svg.qtpl:40
	qw422016.N().D(translate.Vertical)
	//line templates/svg.qtpl:40
	qw422016.N().S(`)">
    <rect width="`)
	//line templates/svg.qtpl:41
	qw422016.N().D(configuration.RC.Width)
	//line templates/svg.qtpl:41
	qw422016.N().S(`" height="`)
	//line templates/svg.qtpl:41
	qw422016.N().D(configuration.RC.Height)
	//line templates/svg.qtpl:41
	qw422016.N().S(`" style="`)
	//line templates/svg.qtpl:41
	qw422016.E().S(configuration.RC.Style)
	//line templates/svg.qtpl:41
	qw422016.N().S(`"/>
    <svg width="`)
	//line templates/svg.qtpl:42
	qw422016.N().D(configuration.RC.Width)
	//line templates/svg.qtpl:42
	qw422016.N().S(`" height="`)
	//line templates/svg.qtpl:42
	qw422016.N().D(configuration.RC.Height)
	//line templates/svg.qtpl:42
	qw422016.N().S(`">
        <text x="50%" y="70%" text-anchor="middle" font-size="`)
	//line templates/svg.qtpl:43
	qw422016.N().D(configuration.TC.FontSize)
	//line templates/svg.qtpl:43
	qw422016.N().S(`">`)
	//line templates/svg.qtpl:43
	qw422016.E().S(record.Port)
	//line templates/svg.qtpl:43
	qw422016.N().S(`</text>
    </svg>
    `)
	//line templates/svg.qtpl:46
	var (
		h = configuration.RC.Height / 2
		w = configuration.AC.HorizontalLength - configuration.AC.HorizontalShift
	)

	//line templates/svg.qtpl:50
	qw422016.N().S(`
    <g transform="translate(`)
	//line templates/svg.qtpl:51
	qw422016.N().D(configuration.RC.Width)
	//line templates/svg.qtpl:51
	qw422016.N().S(`,0)">
        <line x1="0" y1="`)
	//line templates/svg.qtpl:52
	qw422016.N().D(h)
	//line templates/svg.qtpl:52
	qw422016.N().S(`" x2="`)
	//line templates/svg.qtpl:52
	qw422016.N().D(configuration.AC.HorizontalLength)
	//line templates/svg.qtpl:52
	qw422016.N().S(`" y2="`)
	//line templates/svg.qtpl:52
	qw422016.N().D(h)
	//line templates/svg.qtpl:52
	qw422016.N().S(`" style="`)
	//line templates/svg.qtpl:52
	qw422016.E().S(configuration.AC.Style)
	//line templates/svg.qtpl:52
	qw422016.N().S(`"/>
        <line x1="`)
	//line templates/svg.qtpl:53
	qw422016.N().D(configuration.AC.HorizontalLength)
	//line templates/svg.qtpl:53
	qw422016.N().S(`" y1="`)
	//line templates/svg.qtpl:53
	qw422016.N().D(h)
	//line templates/svg.qtpl:53
	qw422016.N().S(`" x2="`)
	//line templates/svg.qtpl:53
	qw422016.N().D(w)
	//line templates/svg.qtpl:53
	qw422016.N().S(`" y2="`)
	//line templates/svg.qtpl:53
	qw422016.N().D(h - configuration.AC.VerticalShift)
	//line templates/svg.qtpl:53
	qw422016.N().S(`" style="`)
	//line templates/svg.qtpl:53
	qw422016.E().S(configuration.AC.Style)
	//line templates/svg.qtpl:53
	qw422016.N().S(`"/>
        <line x1="`)
	//line templates/svg.qtpl:54
	qw422016.N().D(configuration.AC.HorizontalLength)
	//line templates/svg.qtpl:54
	qw422016.N().S(`" y1="`)
	//line templates/svg.qtpl:54
	qw422016.N().D(h)
	//line templates/svg.qtpl:54
	qw422016.N().S(`" x2="`)
	//line templates/svg.qtpl:54
	qw422016.N().D(w)
	//line templates/svg.qtpl:54
	qw422016.N().S(`" y2="`)
	//line templates/svg.qtpl:54
	qw422016.N().D(h + configuration.AC.VerticalShift)
	//line templates/svg.qtpl:54
	qw422016.N().S(`" style="`)
	//line templates/svg.qtpl:54
	qw422016.E().S(configuration.AC.Style)
	//line templates/svg.qtpl:54
	qw422016.N().S(`"/>
        <svg width="`)
	//line templates/svg.qtpl:55
	qw422016.N().D(configuration.AC.HorizontalLength)
	//line templates/svg.qtpl:55
	qw422016.N().S(`" height="`)
	//line templates/svg.qtpl:55
	qw422016.N().D(configuration.RC.Height)
	//line templates/svg.qtpl:55
	qw422016.N().S(`">
            <text x="2%" y="40%" text-anchor="start" font-size="`)
	//line templates/svg.qtpl:56
	qw422016.N().D(configuration.TC.FontSize)
	//line templates/svg.qtpl:56
	qw422016.N().S(`">`)
	//line templates/svg.qtpl:56
	qw422016.E().S(record.Description)
	//line templates/svg.qtpl:56
	qw422016.N().S(`</text>
            <text x="95%" y="40%" text-anchor="end" font-size="`)
	//line templates/svg.qtpl:57
	qw422016.N().D(configuration.TC.FontSize)
	//line templates/svg.qtpl:57
	qw422016.N().S(`">`)
	//line templates/svg.qtpl:57
	qw422016.E().S(record.VLAN)
	//line templates/svg.qtpl:57
	qw422016.N().S(`</text>
        </svg>
    </g>
</g>
`)
	//line templates/svg.qtpl:61
}

//line templates/svg.qtpl:61
func WriteRecordRight(qq422016 qtio422016.Writer, record device.Record, translate Translate, configuration Configuration) {
	//line templates/svg.qtpl:61
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/svg.qtpl:61
	StreamRecordRight(qw422016, record, translate, configuration)
	//line templates/svg.qtpl:61
	qt422016.ReleaseWriter(qw422016)
	//line templates/svg.qtpl:61
}

//line templates/svg.qtpl:61
func RecordRight(record device.Record, translate Translate, configuration Configuration) string {
	//line templates/svg.qtpl:61
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/svg.qtpl:61
	WriteRecordRight(qb422016, record, translate, configuration)
	//line templates/svg.qtpl:61
	qs422016 := string(qb422016.B)
	//line templates/svg.qtpl:61
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/svg.qtpl:61
	return qs422016
	//line templates/svg.qtpl:61
}

//line templates/svg.qtpl:63
func StreamRecordLeft(qw422016 *qt422016.Writer, record device.Record, translate Translate, configuration Configuration) {
	//line templates/svg.qtpl:63
	qw422016.N().S(`
<g transform="translate(`)
	//line templates/svg.qtpl:64
	qw422016.N().D(translate.Horizontal)
	//line templates/svg.qtpl:64
	qw422016.N().S(`,`)
	//line templates/svg.qtpl:64
	qw422016.N().D(translate.Vertical)
	//line templates/svg.qtpl:64
	qw422016.N().S(`)">
    <rect width="`)
	//line templates/svg.qtpl:65
	qw422016.N().D(configuration.RC.Width)
	//line templates/svg.qtpl:65
	qw422016.N().S(`" height="`)
	//line templates/svg.qtpl:65
	qw422016.N().D(configuration.RC.Height)
	//line templates/svg.qtpl:65
	qw422016.N().S(`" style="`)
	//line templates/svg.qtpl:65
	qw422016.E().S(configuration.RC.Style)
	//line templates/svg.qtpl:65
	qw422016.N().S(`"/>
    <svg width="`)
	//line templates/svg.qtpl:66
	qw422016.N().D(configuration.RC.Width)
	//line templates/svg.qtpl:66
	qw422016.N().S(`" height="`)
	//line templates/svg.qtpl:66
	qw422016.N().D(configuration.RC.Height)
	//line templates/svg.qtpl:66
	qw422016.N().S(`">
        <text x="50%" y="70%" text-anchor="middle" font-size="`)
	//line templates/svg.qtpl:67
	qw422016.N().D(configuration.TC.FontSize)
	//line templates/svg.qtpl:67
	qw422016.N().S(`">`)
	//line templates/svg.qtpl:67
	qw422016.E().S(record.Port)
	//line templates/svg.qtpl:67
	qw422016.N().S(`</text>
    </svg>
    `)
	//line templates/svg.qtpl:70
	var (
		h = configuration.RC.Height / 2
		w = configuration.AC.HorizontalLength - configuration.AC.HorizontalShift
	)

	//line templates/svg.qtpl:74
	qw422016.N().S(`
    <line x1="0" y1="`)
	//line templates/svg.qtpl:75
	qw422016.N().D(h)
	//line templates/svg.qtpl:75
	qw422016.N().S(`" x2="`)
	//line templates/svg.qtpl:75
	qw422016.N().D(-configuration.AC.HorizontalLength)
	//line templates/svg.qtpl:75
	qw422016.N().S(`" y2="`)
	//line templates/svg.qtpl:75
	qw422016.N().D(h)
	//line templates/svg.qtpl:75
	qw422016.N().S(`" style="`)
	//line templates/svg.qtpl:75
	qw422016.E().S(configuration.AC.Style)
	//line templates/svg.qtpl:75
	qw422016.N().S(`"/>
    <line x1="`)
	//line templates/svg.qtpl:76
	qw422016.N().D(-configuration.AC.HorizontalLength)
	//line templates/svg.qtpl:76
	qw422016.N().S(`" y1="`)
	//line templates/svg.qtpl:76
	qw422016.N().D(h)
	//line templates/svg.qtpl:76
	qw422016.N().S(`" x2="`)
	//line templates/svg.qtpl:76
	qw422016.N().D(-w)
	//line templates/svg.qtpl:76
	qw422016.N().S(`" y2="`)
	//line templates/svg.qtpl:76
	qw422016.N().D(h - configuration.AC.VerticalShift)
	//line templates/svg.qtpl:76
	qw422016.N().S(`" style="`)
	//line templates/svg.qtpl:76
	qw422016.E().S(configuration.AC.Style)
	//line templates/svg.qtpl:76
	qw422016.N().S(`"/>
    <line x1="`)
	//line templates/svg.qtpl:77
	qw422016.N().D(-configuration.AC.HorizontalLength)
	//line templates/svg.qtpl:77
	qw422016.N().S(`" y1="`)
	//line templates/svg.qtpl:77
	qw422016.N().D(h)
	//line templates/svg.qtpl:77
	qw422016.N().S(`" x2="`)
	//line templates/svg.qtpl:77
	qw422016.N().D(-w)
	//line templates/svg.qtpl:77
	qw422016.N().S(`" y2="`)
	//line templates/svg.qtpl:77
	qw422016.N().D(h + configuration.AC.VerticalShift)
	//line templates/svg.qtpl:77
	qw422016.N().S(`" style="`)
	//line templates/svg.qtpl:77
	qw422016.E().S(configuration.AC.Style)
	//line templates/svg.qtpl:77
	qw422016.N().S(`"/>
    <g transform="translate(`)
	//line templates/svg.qtpl:78
	qw422016.N().D(-configuration.AC.HorizontalLength)
	//line templates/svg.qtpl:78
	qw422016.N().S(`,0)">
        <svg width="`)
	//line templates/svg.qtpl:79
	qw422016.N().D(configuration.AC.HorizontalLength)
	//line templates/svg.qtpl:79
	qw422016.N().S(`" height="`)
	//line templates/svg.qtpl:79
	qw422016.N().D(configuration.RC.Height)
	//line templates/svg.qtpl:79
	qw422016.N().S(`">
            <text x="98%" y="40%" text-anchor="end" font-size="`)
	//line templates/svg.qtpl:80
	qw422016.N().D(configuration.TC.FontSize)
	//line templates/svg.qtpl:80
	qw422016.N().S(`">`)
	//line templates/svg.qtpl:80
	qw422016.E().S(record.Description)
	//line templates/svg.qtpl:80
	qw422016.N().S(`</text>
            <text x="5%" y="40%" text-anchor="start" font-size="`)
	//line templates/svg.qtpl:81
	qw422016.N().D(configuration.TC.FontSize)
	//line templates/svg.qtpl:81
	qw422016.N().S(`">`)
	//line templates/svg.qtpl:81
	qw422016.E().S(record.VLAN)
	//line templates/svg.qtpl:81
	qw422016.N().S(`</text>
        </svg>
    </g>
</g>
`)
	//line templates/svg.qtpl:85
}

//line templates/svg.qtpl:85
func WriteRecordLeft(qq422016 qtio422016.Writer, record device.Record, translate Translate, configuration Configuration) {
	//line templates/svg.qtpl:85
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/svg.qtpl:85
	StreamRecordLeft(qw422016, record, translate, configuration)
	//line templates/svg.qtpl:85
	qt422016.ReleaseWriter(qw422016)
	//line templates/svg.qtpl:85
}

//line templates/svg.qtpl:85
func RecordLeft(record device.Record, translate Translate, configuration Configuration) string {
	//line templates/svg.qtpl:85
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/svg.qtpl:85
	WriteRecordLeft(qb422016, record, translate, configuration)
	//line templates/svg.qtpl:85
	qs422016 := string(qb422016.B)
	//line templates/svg.qtpl:85
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/svg.qtpl:85
	return qs422016
	//line templates/svg.qtpl:85
}

//line templates/svg.qtpl:87
func StreamFooter(qw422016 *qt422016.Writer) {
	//line templates/svg.qtpl:87
	qw422016.N().S(`</svg>`)
}

//line templates/svg.qtpl:87
//line templates/svg.qtpl:87
func WriteFooter(qq422016 qtio422016.Writer) {
	//line templates/svg.qtpl:87
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/svg.qtpl:87
	StreamFooter(qw422016)
	//line templates/svg.qtpl:87
	qt422016.ReleaseWriter(qw422016)
	//line templates/svg.qtpl:87
}

//line templates/svg.qtpl:87
func Footer() string {
	//line templates/svg.qtpl:87
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/svg.qtpl:87
	WriteFooter(qb422016)
	//line templates/svg.qtpl:87
	qs422016 := string(qb422016.B)
	//line templates/svg.qtpl:87
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/svg.qtpl:87
	return qs422016
	//line templates/svg.qtpl:87
}
